### PR TITLE
Fix charge endpoint for custom example

### PR DESCRIPTION
**Pull request by benzguo**
r? @jflinter 

A user pointed out that completing a charge doesn't work in the "Custom" example app [0]. I've fixed this, and tested charging in both example apps.

[0] https://github.com/stripe/stripe-ios/issues/461

### CODE REVIEW

**Comment by jflinter** [comment]
I think this code is pretty hard to read. Can we maybe just update the example apps to use similar parameter naming instead?

**Comment by benzguo** [comment]
I'm not sure that's possible, unless I'm missing something. Our ObjC example requires a backend that just charges a card token, while in our Swift example the backend charges a customer source. 

I definitely agree that this makes the example code more confusing – maybe we should use two different endpoints? Or make separate example backend? Perhaps we should just revisit this as part of revamping our example apps.

**Comment by jflinter** [comment]
I think 2 endpoints seems like a good choice for now.

**Comment by benzguo** [comment]
cool – I've added a new endpoint, and updated the Custom example in https://github.com/stripe/stripe-ios/pull/470

**Comment by jflinter** [comment]
LGTM

**Pull request merged**
